Models/DeviceInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Login_Application.Models
{
    public class Device
    {
        public string SlNo { get; set; }
        public string DeviceType { get; set; }
        public string DeviceName { get; set; }
        public string DeviceDetail { get; set; }
    }
}

Models/DropdownClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Login_Application.Models
{
    public class DropdownClass
    {
        Login_ApplicationEntities db = new Login_ApplicationEntities();
        public DropdownClass()
        {
            this.Devices = new List<Device>();
        }
        public List<Device> Devices { set; get; }

        public int Oid { get; set; }
        public int Lid { get; set; }
        public int Sid { get; set; }

        public int Did { get; set; }
    }
}

Models/LoginClass.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Login_Application.Models
{
    public class LoginClass
    {   
        [Required(ErrorMessage = "Please Enter Username")]
        [Display(Name = "Username")]
        public string username { get; set; }
        [Required(ErrorMessage = "Please Enter password")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
    }
}

Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login_Application.Controllers
{
        public class DeviceController : Controller
        {
            // GET: Device
            [HttpGet]
            public ActionResult ViewDevicesById(string slno)
            {
                List<Device> lstDevices = new List<Device>();
                DeviceDal dalObj = new DeviceDal();
                var result = dalObj.FetchDevicesById(@slno);
                foreach (var item in result)
                {
                    lstDevices.Add(new Device()
                    {
                        SlNo = item.SlNo,
                        DeviceType = item.DeviceType,
                        DeviceName = item.DeviceName,
                        DeviceDetail = item.DeviceDetail
                    });
                }
                return View(lstDevices);
            }
    public ActionResult Close()
        {
            Session.Clear();
            return RedirectToAction("Index", "Dropdown");
        }
    }
}

Controllers/DropdownController.cs
using Login_Application.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login_Application.Controllers
{
    public class DropdownController : Controller
    {
        // GET: Dropdown
        public ActionResult Index()
        {
            Login_ApplicationEntities sd = new Login_ApplicationEntities();
            ViewBag.OrganizationList = new SelectList(GetOrganizationList(), "Oid", "Oname");
            return View();
        }
        public List<organization> GetOrganizationList()
        {
            Login_ApplicationEntities sd = new Login_ApplicationEntities();
            List<organization> organizations = sd.organizations.ToList();
            return organizations;
        }

        public ActionResult GetLocationList(int Oid)
        {
            Login_ApplicationEntities sd = new Login_ApplicationEntities();
            List<Location> selectList = sd.Locations.Where(x => x.Oid == Oid).ToList();
            ViewBag.Llist = new SelectList(selectList, "Lid", "Lname");
            return PartialView("DisplayLocation");
        }
        public ActionResult GetSiteList(int Lid)
        {
            Login_ApplicationEntities sd = new Login_ApplicationEntities();
            List<Site> selectList = sd.Sites.Where(x => x.Lid == Lid).ToList();
            ViewBag.Slist = new SelectList(selectList, "Sid", "Sname");
            return PartialView("DisplaySite");
        }
        public ActionResult GetDeviceList(int Sid)
        {
            Login_ApplicationEntities sd = new Login_ApplicationEntities();
            List<Device> selectList = sd.Devices.Where(x => x.Sid == Sid).ToList();
            ViewBag.Dlist = new SelectList(selectList, "Did", "Dname");
            return PartialView("DisplayDevice");
        }
        public ActionResult Devices(int id)
        {
           Login_ApplicationEntities db = new Login_ApplicationEntities();

            DropdownClass empss = new DropdownClass();
            empss.Devices = db.Devices.ToList();
            var value = empss.Devices.Single(d => d.Did == id);
            return View(value);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login_Application.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/UserLoginController.cs
using Login_Application.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login_Application.Controllers
{
    public class UserLoginController : Controller
    {
        // GET: UserLogin
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(LoginClass lc)
        {
            string conStr = ConfigurationManager.ConnectionStrings["Constr"].ConnectionString;
            SqlConnection sqlcon = new SqlConnection(conStr);
            string sqlquery = "SELECT TOP (1000) [username], [password] FROM[Login].[dbo].[UserLogin]";
            sqlcon.Open();
            SqlCommand sqlcom = new SqlCommand(sqlquery, sqlcon);
            sqlcom.Parameters.AddWithValue("@username", lc.username);
            sqlcom.Parameters.AddWithValue("@password", lc.password);
            SqlDataReader sqdr = sqlcom.ExecuteReader();
            if (sqdr.Read())
            {
                Session["username"] = lc.username.ToString();
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                ViewData["Message"] = "Login Details Failed";
            }
            sqlcon.Close();

            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "UserLogin");
        }
    }
}

Views/Device/GetDeviceInfo.cshtml
@model Login_Application.Models.DeviceInfo

@{
    ViewBag.Title = "ViewDevicesById";
}
<div style="color:darkslategrey">
    <h2><u>Devices</u></h2>
</div>
<br />
<br />
<table class="table">
    @*<td>
            <tr>
              <b>Sl No. </b>  @Html.TextBox("SlNo")
            </tr>
        <br />
            <tr>
                <b>Device Type: </b>  @Html.TextBox("DeviceType")
            </tr>
        <br />
            <tr>
                <b>Device Name: </b>  @Html.TextBox("DeviceName")
            </tr>
        <br />
            <tr>
                <b>Device Detail: </b>  @Html.TextBox("DeviceDetail") <input type="submit" value="Device Detail" />
            </tr>
        <br />
            <tr></tr>
        </td>*@

    @foreach (var item in Model)
    {
        <td>
        <tr>
            <div style="color:blueviolet; font-size:large; font-style:inherit">

                <b>Sl No: </b>  @Html.TextBoxFor(modelItem => item.SlNo, new { @readonly = "readonly" })
            </div>
        </tr>

        <br />
        <tr>
            <div style="color:#8e0b7b; font-size:initial; font-style:inherit">


                <b>Device Type: </b>   @Html.TextBoxFor(modelItem => item.DeviceType, new { @readonly = "readonly" })
            </div>
        </tr>
        <br />
        <tr>
            <div style="color: #8e0b7b; font-size: initial; font-style: inherit ">

                <b>Device Name: </b>    @Html.TextBoxFor(modelItem => item.DeviceName, new { @readonly = "readonly" })
            </div>
        </tr>
        <br />
        <tr>
            <div style="color: #8e0b7b; font-size: initial; font-style: inherit ">

                <b>Device Details: </b>   @Html.TextBoxFor(modelItem => item.DeviceDetail, new { @readonly = "readonly" })
            </div>
        </tr>

        </td>
    }

</table>

Views/Device/ViewDevicesById.cshtml
@model IEnumerable<Login_Application.Models.Device>

@{
    ViewBag.Title = "ViewDevicesById";
}
<div style="color:darkslategrey">
    <h2><u>Devices</u></h2>
</div>
<br />
<br />
<table class="table">
    @*<td>
            <tr>
              <b>Sl No. </b>  @Html.TextBox("SlNo")
            </tr>
        <br />
            <tr>
                <b>Device Type: </b>  @Html.TextBox("DeviceType")
            </tr>
        <br />
            <tr>
                <b>Device Name: </b>  @Html.TextBox("DeviceName")
            </tr>
        <br />
            <tr>
                <b>Device Detail: </b>  @Html.TextBox("DeviceDetail") <input type="submit" value="Device Detail" />
            </tr>
        <br />
            <tr></tr>
        </td>*@

    @foreach (var item in Model)
    {
        <td>
        <tr>
            <div style="color:blueviolet; font-size:large; font-style:inherit">

                <b>Sl No: </b>  @Html.TextBoxFor(modelItem => item.SlNo, new { @readonly = "readonly" })
            </div>
        </tr>

        <br />
        <tr>
            <div style="color:#8e0b7b; font-size:initial; font-style:inherit">


                <b>Device Type: </b>   @Html.TextBoxFor(modelItem => item.DeviceType, new { @readonly = "readonly" })
            </div>
        </tr>
        <br />
        <tr>
            <div style="color: #8e0b7b; font-size: initial; font-style: inherit ">

                <b>Device Name: </b>    @Html.TextBoxFor(modelItem => item.DeviceName, new { @readonly = "readonly" })
            </div>
        </tr>
        <br />
        <tr>
            <div style="color: #8e0b7b; font-size: initial; font-style: inherit ">

                <b>Device Details: </b>   @Html.TextBoxFor(modelItem => item.DeviceDetail, new { @readonly = "readonly" })
            </div>
        </tr>

        </td>
    }

</table>

Views/Dropdown/Devices.cshtml
@model Login_Application.Models.DropdownClass

Views/Dropdown/Index.cshtml
@model Login_Application.Models.DropdownClass
@{
    ViewBag.Title = "Index";
}

<header>
    <div class="w3-container w3-teal">
        <center><h2>DASHBOARD</h2></center>
        <input type="button" class="btn btn-primary" value="Logout" style="float:right !important" onclick="location.href='@Url.Action("Logout", "UserLogin")'" />
    </div>
</header>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        body {
            font-family: "Times New Roman", Georgia, Serif;
            padding: 25px;
        }

        h1, h2, h3, h4, h5, h6 {
            text-align: center;
            text-size-adjust: auto;
            text-decoration: underline;
            text-shadow: inherit;
            font-family: "Playfair Display";
            letter-spacing: 5px;
        }

        .div-table {
            display: table;
            width: auto;
            background-color: #c0ced3;
            border: 1px solid #c0ced3;
            border-spacing: 5px;
        }

        .div-table-row {
            display: table-row;
            width: auto;
            clear: both;
        }

        .div-table-col {
            float: left;
            display: table-column;
            width: 200px;
            background-color: #ccc;
        }

        aside {
            text-decoration-style: solid;
            text-size-adjust: 300%;
            text-align: center;
            text-indent: each-line;
            float: left;
            width: 25%;
            height: 415px;
            background: #ccc;
            padding: 50px;
        }
    </style>
</head>
<body>
    <aside id="side">
        <a href="#"><p>Dashboard</p></a>
        <a href="#"><p>Report</p></a>
        <a href="#">User Details</a>
    </aside>
</body>
</html>

<br />

<center>
    <div style="color:purple;">
        @Html.Label("Organization")
    </div>
    @if (ViewBag.OrganizationList != null)
    {
        @Html.DropDownListFor(m => m.Oid, ViewBag.OrganizationList as SelectList, "-- Select Organization --", new { @class = "form-control" })
    }
</center>

<br />

<center>
    <div style="color:purple;">
        @Html.Label("Location")
    </div>
    @Html.DropDownListFor(m => m.Lid, new SelectList(""), "-- Select Location --", new { @class = "form-control" })
</center>

<br />

<center>
    <div style="color:purple;">
        @Html.Label("Site")
    </div>
    @Html.DropDownListFor(m => m.Sid, new SelectList(""), "-- Select Site --", new { @class = "form-control" })
</center>

<br />

<center>

    <div style="color:purple;">
        @Html.Label("Devices")
    </div>
    <style>
        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 50%;
        }

            #customers td, #customers th {
                border: 1px solid #ddd;
                padding: 8px;
            }

            #customers tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            #customers tr:hover {
                background-color: #ddd;
            }

            #customers th {
                padding-top: 12px;
                padding-bottom: 12px;
                text-align: Center;
                background-color: #ccc;
                color: white;
            }
    </style>
    @*<table id="customers">
        <tr class=" div-table-row">
            <th>Device Name</th>

        </tr>
    </table>*@
    @*@Html.DropDownListFor(m => m.Did, new SelectList(""), "-- Select Devices --", new { @class = "form-control" })*@
    <p> <div id="Did"></div> <p>

</center>

<br />

<center>

     <div class="form-group">
            <center>
                <input type="button" class="btn btn-primary" value="Submit" style="float:!important" onclick="location.href='@Url.Action("GetDeviceInfo", "Device")?Did'"/>
            </center>
        </div> 
</center>
<br />

<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#Oid").change(function () {
            if (document.getElementById("Oid").selectedIndex == 0) {
                $("#Lid").empty();
                $("#Sid").empty();
                $("#Did").empty();
            }
            else {
                var OrgId = $(this).val();
                debugger
                $.ajax({
                    type: "post",
                    url: "/Dropdown/GetLocationList?Oid=" + OrgId,
                    contentType: "html",
                    success: function (response) {
                        debugger
                        $("#Lid").empty();
                        $("#Lid").append(response);
                    }

                })
            }
        })
        $("#Lid").change(function () {
            if (document.getElementById("Lid").selectedIndex == 0) {
                $("#Sid").empty();
                $("#Did").empty();
            }
            else {
                var LocId = $(this).val();
                debugger
                $.ajax({
                    type: "post",
                    url: "/Dropdown/GetSiteList?Lid=" + LocId,
                    contentType: "html",
                    success: function (response) {
                        debugger
                        $("#Sid").empty();
                        $("#Sid").append(response);
                    }
                })
            }
        })
        $("#Sid").change(function () {
            if (document.getElementById("Sid").selectedIndex == 0) {
                $("#Did").empty();
            }
            else {
                var SitId = $(this).val();
                debugger
              $.ajax({
                  type: "post",
                  url: "/Dropdown/GetDeviceList?Sid=" + SitId,
                    contentType: "html",
                   success: function (response) {
                       debugger
                       $("#Did").empty();
                       $("#Did").append(`<a href="${response}"></a>`)
                       //$("#Did").append(response);
                        }
                    })
                }
            })
        })
</script>

<script> //commented

    @*@Html.ActionLink("Click here", // <-- Link text
        "About", // <-- Action Method Name
        "Home", // <-- Controller Name
        null, // <-- Route value
        null // <-- htmlArguments
    ) *@
                       //$("#Did").attr('href', /Dashboard/Devices);

    @*var SitId = $(this).val();
    debugger
    $('#Did').on('click', function () {
        $.ajax({
            type: "post",
            url: "/Dropdown/GetDeviceList?Sid=" + SitId,
            contentType: "html",
            async: false,
            dataType: 'html',
            url: '@Url.Action("Devices", "Dashboard")'
        }).success(function (partialView) {
            //var result = $(partialView).find("#linkDelte").append('a href="#">Link</a>');

            $('#Did').append(result);

        });
    });*@
                     //  $(document).ready(function () {
                       //     $('#myAnchor').click(function () {
                       //        window.location.href = 'index.php';
//                        //    });
//                        //})
//                        /*                            $($("#Did").append(response))[0].click();*/
//                        /*                        $($("#Did").append(response))[0].click();*/
//                        //$($("#Did").append(response)).trigger('click');
//                            $($("#Did").append(response)).click(function (event) {
//                                var link = $(this);
//                                var target = link.attr("target");

//                                if ($.trim(target).length > 0) {
//                                    window.open(link.attr("href"), target);
//                                }
//                                else {
//                                    window.location = link.attr("href");
//                                }

//                                event.preventDefault();
//                            });
///*                            jQuery('<div><a href="http://example.com"></a></div>').prependTo($("#Did").append(response));*/
//                            //$("tableSelector").delegate("tr.rows", "click", function () {
//                            //    alert("Click!");
//                            //});
//                            //$("#Did").click(function (response) {

//                            //    $(this).url("/Device/GetDeviceInfo?Did=" + Did)
                          //})

    @* <a href="#" id="myAnchor">Click me</a> *@

@* <div class="form-group">
        <center>
            <input type="button" class="btn btn-primary" value="Submit" style="float:!important" onclick="location.href='@Url.Action(" Index", "Device")'" />
        </center>
    </div> *@

</script>

Views/Dropdown/ShowGrid.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowGrid</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

    <script>
        $(document).ready(function () {
            $("#demoGrid").DataTable({

                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once
                "pageLength": 5,

                "ajax": {
                    "url": "/Demo/LoadData",
                    "type": "POST",
                    "datatype": "json"
                },

                "columnDefs":
                    [{
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "targets": [7],
                        "searchable": false,
                        "orderable": false
                    },
                    {
                        "targets": [8],
                        "searchable": false,
                        "orderable": false
                    },
                    {
                        "targets": [9],
                        "searchable": false,
                        "orderable": false
                    }],

                "columns": [
                    { "data": "CustomerID", "name": "CustomerID", "autoWidth": true },
                    { "data": "CompanyName", "name": "CompanyName", "autoWidth": true },
                    { "data": "ContactName", "title": "ContactName", "name": "ContactName", "autoWidth": true },
                    { "data": "ContactTitle", "name": "ContactTitle", "autoWidth": true },
                    { "data": "City", "name": "City", "autoWidth": true },
                    { "data": "PostalCode", "name": "PostalCode", "autoWidth": true },
                    { "data": "Country", "name": "Country", "autoWidth": true },
                    { "data": "Phone", "name": "Phone", "title": "Status", "autoWidth": true },
                    {
                        "render": function (data, type, full, meta) { return '<a class="btn btn-info" href="/Demo/Edit/' + full.CustomerID + '">Edit</a>'; }
                    },
                    {
                        data: null, render: function (data, type, row) {
                            return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + row.CustomerID + "'); >Delete</a>";
                        }
                    },

                ]

            });
        });
    </script>

</head>
<body>
    <div class="container">
        <br />
        <div style="width:90%; margin:0 auto;">
            <table id="demoGrid" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>CustomerID</th>
                        <th>CompanyName</th>
                        <th>ContactName</th>
                        <th>ContactTitle</th>
                        <th>City</th>
                        <th>PostalCode</th>
                        <th>Country</th>
                        <th>Phone</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</body>
</html>  

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/DisplayDevice.cshtml
@model Login_Application.Device

<option value=""></option>

<br>
@if (ViewBag.Dlist != null)
{
    foreach (var item in ViewBag.Dlist)
    {
        //<option value="@item.Value">@item.Text</option>
        <td>@item.Text</td>
        @*<div>
            <ul>
                <li>@Html.ActionLink(@item.Text, "Devices", new { id = Device.Did })</li>
            </ul>
        </div>*@

    }
}

Views/Shared/DisplayLocation.cshtml
@model Login_Application.Location

<option value="">-- Select Location --</option>

@if(ViewBag.Llist != null)
{
    foreach (var item in ViewBag.Llist)
                {
                    <option value="@item.Value">@item.Text</option>
                }
}

Views/Shared/DisplaySite.cshtml
@model Login_Application.Site

<option value="">-- Select Sites --</option>

@if (ViewBag.Slist != null)
{
    foreach (var item in ViewBag.Slist)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/UserLogin/Index.cshtml
@model Login_Application.Models.LoginClass

@{ ViewBag.Title = "Login"; }
<h2><text> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</text>User Login</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-primary" style="background-color: indigo" />
                <input type="submit" value="Cancel" class="btn btn-primary" style="background-color: indigo" />
            </div>
        </div>
        <h3>@Html.ViewData["Message"]</h3>
    </div>}





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}